/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarsForSaleRouteImport } from './routes/cars-for-sale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsForSaleIdRouteImport } from './routes/cars-for-sale.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsForSaleRoute = CarsForSaleRouteImport.update({
  id: '/cars-for-sale',
  path: '/cars-for-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsForSaleIdRoute = CarsForSaleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarsForSaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cars-for-sale': typeof CarsForSaleRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/cars-for-sale/$id': typeof CarsForSaleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cars-for-sale': typeof CarsForSaleRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/cars-for-sale/$id': typeof CarsForSaleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cars-for-sale': typeof CarsForSaleRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/cars-for-sale/$id': typeof CarsForSaleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cars-for-sale'
    | '/contact'
    | '/services'
    | '/cars-for-sale/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cars-for-sale' | '/contact' | '/services' | '/cars-for-sale/$id'
  id:
    | '__root__'
    | '/'
    | '/cars-for-sale'
    | '/contact'
    | '/services'
    | '/cars-for-sale/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarsForSaleRoute: typeof CarsForSaleRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars-for-sale': {
      id: '/cars-for-sale'
      path: '/cars-for-sale'
      fullPath: '/cars-for-sale'
      preLoaderRoute: typeof CarsForSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars-for-sale/$id': {
      id: '/cars-for-sale/$id'
      path: '/$id'
      fullPath: '/cars-for-sale/$id'
      preLoaderRoute: typeof CarsForSaleIdRouteImport
      parentRoute: typeof CarsForSaleRoute
    }
  }
}

interface CarsForSaleRouteChildren {
  CarsForSaleIdRoute: typeof CarsForSaleIdRoute
}

const CarsForSaleRouteChildren: CarsForSaleRouteChildren = {
  CarsForSaleIdRoute: CarsForSaleIdRoute,
}

const CarsForSaleRouteWithChildren = CarsForSaleRoute._addFileChildren(
  CarsForSaleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarsForSaleRoute: CarsForSaleRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
