/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarsForSaleRouteImport } from './routes/cars-for-sale'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusTokenRouteImport } from './routes/status.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as CarsForSaleIdRouteImport } from './routes/cars-for-sale.$id'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedMechanicRouteImport } from './routes/_authenticated/mechanic'
import { Route as AuthenticatedCustomerPortalRouteImport } from './routes/_authenticated/customer-portal'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AuthenticatedCustomerPortalMessagesRouteImport } from './routes/_authenticated/customer-portal.messages'
import { Route as AdminAdminWorkOrdersRouteImport } from './routes/_admin/admin.work-orders'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin.reports'
import { Route as AdminAdminMessagesRouteImport } from './routes/_admin/admin.messages'
import { Route as AdminAdminInvoicesRouteImport } from './routes/_admin/admin.invoices'
import { Route as AdminAdminCustomersRouteImport } from './routes/_admin/admin.customers'
import { Route as AdminAdminCarsRouteImport } from './routes/_admin/admin.cars'
import { Route as AdminAdminBookingsRouteImport } from './routes/_admin/admin.bookings'
import { Route as AdminAdminAccountsRouteImport } from './routes/_admin/admin.accounts'
import { Route as AdminAdminCustomersIdRouteImport } from './routes/_admin/admin.customers.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsForSaleRoute = CarsForSaleRouteImport.update({
  id: '/cars-for-sale',
  path: '/cars-for-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusTokenRoute = StatusTokenRouteImport.update({
  id: '/status/$token',
  path: '/status/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsForSaleIdRoute = CarsForSaleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarsForSaleRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMechanicRoute = AuthenticatedMechanicRouteImport.update({
  id: '/mechanic',
  path: '/mechanic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomerPortalRoute =
  AuthenticatedCustomerPortalRouteImport.update({
    id: '/customer-portal',
    path: '/customer-portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedCustomerPortalMessagesRoute =
  AuthenticatedCustomerPortalMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedCustomerPortalRoute,
  } as any)
const AdminAdminWorkOrdersRoute = AdminAdminWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminInvoicesRoute = AdminAdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCustomersRoute = AdminAdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCarsRoute = AdminAdminCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBookingsRoute = AdminAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAccountsRoute = AdminAdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCustomersIdRoute = AdminAdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/cars-for-sale': typeof CarsForSaleRouteWithChildren
  '/contact': typeof ContactRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/customer-portal': typeof AuthenticatedCustomerPortalRouteWithChildren
  '/mechanic': typeof AuthenticatedMechanicRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/cars-for-sale/$id': typeof CarsForSaleIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/status/$token': typeof StatusTokenRoute
  '/admin/accounts': typeof AdminAdminAccountsRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/cars': typeof AdminAdminCarsRoute
  '/admin/customers': typeof AdminAdminCustomersRouteWithChildren
  '/admin/invoices': typeof AdminAdminInvoicesRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/work-orders': typeof AdminAdminWorkOrdersRoute
  '/customer-portal/messages': typeof AuthenticatedCustomerPortalMessagesRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/customers/$id': typeof AdminAdminCustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/cars-for-sale': typeof CarsForSaleRouteWithChildren
  '/contact': typeof ContactRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/customer-portal': typeof AuthenticatedCustomerPortalRouteWithChildren
  '/mechanic': typeof AuthenticatedMechanicRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/cars-for-sale/$id': typeof CarsForSaleIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/status/$token': typeof StatusTokenRoute
  '/admin/accounts': typeof AdminAdminAccountsRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/cars': typeof AdminAdminCarsRoute
  '/admin/customers': typeof AdminAdminCustomersRouteWithChildren
  '/admin/invoices': typeof AdminAdminInvoicesRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/work-orders': typeof AdminAdminWorkOrdersRoute
  '/customer-portal/messages': typeof AuthenticatedCustomerPortalMessagesRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/customers/$id': typeof AdminAdminCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/book': typeof BookRoute
  '/cars-for-sale': typeof CarsForSaleRouteWithChildren
  '/contact': typeof ContactRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/customer-portal': typeof AuthenticatedCustomerPortalRouteWithChildren
  '/_authenticated/mechanic': typeof AuthenticatedMechanicRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/cars-for-sale/$id': typeof CarsForSaleIdRoute
  '/pay/$token': typeof PayTokenRoute
  '/status/$token': typeof StatusTokenRoute
  '/_admin/admin/accounts': typeof AdminAdminAccountsRoute
  '/_admin/admin/bookings': typeof AdminAdminBookingsRoute
  '/_admin/admin/cars': typeof AdminAdminCarsRoute
  '/_admin/admin/customers': typeof AdminAdminCustomersRouteWithChildren
  '/_admin/admin/invoices': typeof AdminAdminInvoicesRoute
  '/_admin/admin/messages': typeof AdminAdminMessagesRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/work-orders': typeof AdminAdminWorkOrdersRoute
  '/_authenticated/customer-portal/messages': typeof AuthenticatedCustomerPortalMessagesRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/customers/$id': typeof AdminAdminCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/cars-for-sale'
    | '/contact'
    | '/install'
    | '/login'
    | '/services'
    | '/settings'
    | '/signup'
    | '/admin'
    | '/customer-portal'
    | '/mechanic'
    | '/portal'
    | '/cars-for-sale/$id'
    | '/pay/$token'
    | '/status/$token'
    | '/admin/accounts'
    | '/admin/bookings'
    | '/admin/cars'
    | '/admin/customers'
    | '/admin/invoices'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/work-orders'
    | '/customer-portal/messages'
    | '/admin/'
    | '/admin/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/cars-for-sale'
    | '/contact'
    | '/install'
    | '/login'
    | '/services'
    | '/settings'
    | '/signup'
    | '/customer-portal'
    | '/mechanic'
    | '/portal'
    | '/cars-for-sale/$id'
    | '/pay/$token'
    | '/status/$token'
    | '/admin/accounts'
    | '/admin/bookings'
    | '/admin/cars'
    | '/admin/customers'
    | '/admin/invoices'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/work-orders'
    | '/customer-portal/messages'
    | '/admin'
    | '/admin/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/book'
    | '/cars-for-sale'
    | '/contact'
    | '/install'
    | '/login'
    | '/services'
    | '/settings'
    | '/signup'
    | '/_admin/admin'
    | '/_authenticated/customer-portal'
    | '/_authenticated/mechanic'
    | '/_authenticated/portal'
    | '/cars-for-sale/$id'
    | '/pay/$token'
    | '/status/$token'
    | '/_admin/admin/accounts'
    | '/_admin/admin/bookings'
    | '/_admin/admin/cars'
    | '/_admin/admin/customers'
    | '/_admin/admin/invoices'
    | '/_admin/admin/messages'
    | '/_admin/admin/reports'
    | '/_admin/admin/work-orders'
    | '/_authenticated/customer-portal/messages'
    | '/_admin/admin/'
    | '/_admin/admin/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BookRoute: typeof BookRoute
  CarsForSaleRoute: typeof CarsForSaleRouteWithChildren
  ContactRoute: typeof ContactRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  PayTokenRoute: typeof PayTokenRoute
  StatusTokenRoute: typeof StatusTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars-for-sale': {
      id: '/cars-for-sale'
      path: '/cars-for-sale'
      fullPath: '/cars-for-sale'
      preLoaderRoute: typeof CarsForSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/$token': {
      id: '/status/$token'
      path: '/status/$token'
      fullPath: '/status/$token'
      preLoaderRoute: typeof StatusTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars-for-sale/$id': {
      id: '/cars-for-sale/$id'
      path: '/$id'
      fullPath: '/cars-for-sale/$id'
      preLoaderRoute: typeof CarsForSaleIdRouteImport
      parentRoute: typeof CarsForSaleRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mechanic': {
      id: '/_authenticated/mechanic'
      path: '/mechanic'
      fullPath: '/mechanic'
      preLoaderRoute: typeof AuthenticatedMechanicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customer-portal': {
      id: '/_authenticated/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof AuthenticatedCustomerPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/customer-portal/messages': {
      id: '/_authenticated/customer-portal/messages'
      path: '/messages'
      fullPath: '/customer-portal/messages'
      preLoaderRoute: typeof AuthenticatedCustomerPortalMessagesRouteImport
      parentRoute: typeof AuthenticatedCustomerPortalRoute
    }
    '/_admin/admin/work-orders': {
      id: '/_admin/admin/work-orders'
      path: '/work-orders'
      fullPath: '/admin/work-orders'
      preLoaderRoute: typeof AdminAdminWorkOrdersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/messages': {
      id: '/_admin/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/invoices': {
      id: '/_admin/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminAdminInvoicesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/customers': {
      id: '/_admin/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAdminCustomersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/cars': {
      id: '/_admin/admin/cars'
      path: '/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminAdminCarsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/bookings': {
      id: '/_admin/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminAdminBookingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/accounts': {
      id: '/_admin/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAdminAccountsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/customers/$id': {
      id: '/_admin/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminAdminCustomersIdRouteImport
      parentRoute: typeof AdminAdminCustomersRoute
    }
  }
}

interface AdminAdminCustomersRouteChildren {
  AdminAdminCustomersIdRoute: typeof AdminAdminCustomersIdRoute
}

const AdminAdminCustomersRouteChildren: AdminAdminCustomersRouteChildren = {
  AdminAdminCustomersIdRoute: AdminAdminCustomersIdRoute,
}

const AdminAdminCustomersRouteWithChildren =
  AdminAdminCustomersRoute._addFileChildren(AdminAdminCustomersRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminAccountsRoute: typeof AdminAdminAccountsRoute
  AdminAdminBookingsRoute: typeof AdminAdminBookingsRoute
  AdminAdminCarsRoute: typeof AdminAdminCarsRoute
  AdminAdminCustomersRoute: typeof AdminAdminCustomersRouteWithChildren
  AdminAdminInvoicesRoute: typeof AdminAdminInvoicesRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminWorkOrdersRoute: typeof AdminAdminWorkOrdersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAccountsRoute: AdminAdminAccountsRoute,
  AdminAdminBookingsRoute: AdminAdminBookingsRoute,
  AdminAdminCarsRoute: AdminAdminCarsRoute,
  AdminAdminCustomersRoute: AdminAdminCustomersRouteWithChildren,
  AdminAdminInvoicesRoute: AdminAdminInvoicesRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminWorkOrdersRoute: AdminAdminWorkOrdersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedCustomerPortalRouteChildren {
  AuthenticatedCustomerPortalMessagesRoute: typeof AuthenticatedCustomerPortalMessagesRoute
}

const AuthenticatedCustomerPortalRouteChildren: AuthenticatedCustomerPortalRouteChildren =
  {
    AuthenticatedCustomerPortalMessagesRoute:
      AuthenticatedCustomerPortalMessagesRoute,
  }

const AuthenticatedCustomerPortalRouteWithChildren =
  AuthenticatedCustomerPortalRoute._addFileChildren(
    AuthenticatedCustomerPortalRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCustomerPortalRoute: typeof AuthenticatedCustomerPortalRouteWithChildren
  AuthenticatedMechanicRoute: typeof AuthenticatedMechanicRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCustomerPortalRoute:
    AuthenticatedCustomerPortalRouteWithChildren,
  AuthenticatedMechanicRoute: AuthenticatedMechanicRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CarsForSaleRouteChildren {
  CarsForSaleIdRoute: typeof CarsForSaleIdRoute
}

const CarsForSaleRouteChildren: CarsForSaleRouteChildren = {
  CarsForSaleIdRoute: CarsForSaleIdRoute,
}

const CarsForSaleRouteWithChildren = CarsForSaleRoute._addFileChildren(
  CarsForSaleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BookRoute: BookRoute,
  CarsForSaleRoute: CarsForSaleRouteWithChildren,
  ContactRoute: ContactRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  PayTokenRoute: PayTokenRoute,
  StatusTokenRoute: StatusTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
